// site/vue3/src/components/Todo/Index.vue
<script lang="ts" setup>
import { computed, ref } from "vue";
import { $Notification } from "@/utils/toast.ts";
import { Modal } from "@arco-design/web-vue";
import { TYPE_LIST } from "@/utils/todo.ts";
const props = defineProps({ list: Array });
const emit = defineEmits(["add", "del"]);
const inputVal = ref("");
const todoList = computed(() => props.list as TYPE_LIST);
const onAdd = function () {
  if (!inputVal.value) return $Notification({ content: "请输入内容！", type: "warning" });
  emit("add", inputVal.value);
  inputVal.value = ""; // after enter we should clear this value
};
const onDel = function (content: string) {
  Modal.confirm({
    title: "提示",
    content: "您确定要删除吗？删除后不可恢复",
    onOk: () => emit("del", content),
  });
};
</script>

<template>
  <div class="todosPage">
    <div>
      <a-input-search
        class="head-input"
        :style="{ width: '320px' }"
        v-model="inputVal"
        @search="onAdd"
        placeholder="请输入"
        button-text="添加"
        search-button
      />
    </div>
    <template v-if="todoList.length">
      <div class="justify-between align-center item" v-for="(item, index) in todoList" :key="index">
        <span class="content">{{ item }}</span>
        <a-button type="text" status="danger" @click="onDel(item)">删除</a-button>
      </div>
    </template>
    <a-empty style="margin-top: 48px" v-else />
  </div>
</template>

// site/react/src/components/Todo/index.tsx
import React, { useState } from "react";
import { $Notification } from "@/utils/toast.ts";
import { Button, Input, Modal, Empty } from "@arco-design/web-react";
import { TYPE_LIST } from "@/utils/todo.ts";

const InputSearch = Input.Search;

interface INF_PROPS {
  list: TYPE_LIST;
  add: Function;
  del: Function;
}
export default function Todo(props: INF_PROPS): React.JSX.Element {
  const [inputVal, setInputVal] = useState("");
  const { list, del, add } = props;
  const todoList = list;
  const onAdd = function () {
    if (!inputVal) return $Notification({ content: "请输入内容！", type: "warning" });
    add(inputVal);
    setInputVal(""); // after enter we should clear this value
  };

  const onDel = function (content: string) {
    Modal.confirm({
      title: "提示",
      content: "您确定要删除吗？删除后不可恢复",
      onOk: () => del(content),
    });
  };
  return (
    <div className="todosPage">
      <InputSearch
        searchButton="添加"
        placeholder="请输入"
        style={{ width: "320px" }}
        onChange={(e) => setInputVal(e)}
        onSearch={onAdd}
        className="head-input"
        value={inputVal}
      />
      {todoList.length ? (
        <>
          {todoList.map((item, index) => (
            <div className="justify-between align-center item" key={item + index}>
              <span className="content">{item}</span>
              <Button type="text" status="danger" onClick={() => onDel(item)}>
                删除
              </Button>
            </div>
          ))}
        </>
      ) : (
        <Empty style={{ marginTop: "48px" }} />
      )}
    </div>
  );
}
