// site/react/src/pages/storeUse/index.tsx
import React from "react";
import Todo from "@/components/Todo";
import { observer } from "mobx-react";
import todoStore from "@/store/todoList.ts";
import CodeDemo from "@/components/CodeDemo";

const StoreUse = function (): React.JSX.Element {
  const todoList = todoStore.todos;
  const add = function (content: string) {
    todoStore.createItem(content);
  };
  const del = function (content: string) {
    todoStore.removeItem(content);
  };
  return (
    <>
      <Todo list={todoList} add={add} del={del} />
      <CodeDemo fileList={["@/components/Todo/index.tsx"]} />
    </>
  );
};
export default observer(StoreUse);

// site/vue3/src/pages/storeUse/index.vue
<script lang="ts" setup>
import CodeDemo from "@/components/CodeDemo/index.vue";
import Todo from "@/components/Todo/Index.vue";
import { computed } from "vue";
import useTodoStore from "@/store/todoList.ts";
const todoStore = useTodoStore()
const todoList = computed(()=> todoStore.getTodos)
const del = function (content: string) {
  todoStore.removeItem(content)
};
const add = function (content: string) {
  todoStore.createItem(content)
};
</script>
<template>
  <Todo :list="todoList" @add="add" @del="del"  />
  <CodeDemo :codeData="null" />
</template>
