// site/react/src/pages/baseUse/index.tsx
import React, { useState } from "react";
import Todo from "@/components/Todo";
import { addItem, TYPE_LIST, delItem, getList } from "@/utils/todo.ts";

export default function BaseUse(): JSX.Element {
  const [todoList, setTodoList] = useState<TYPE_LIST>(getList());

  const del = function (content: string) {
    delItem(setTodoList, todoList, content)
  };
  const add = function (content: string) {
    addItem(setTodoList, todoList, content)
  };
  return <Todo list={todoList}  add={add} del={del}  />;
}

// site/vue3/src/pages/baseUse/index.vue
<script lang="ts" setup>
import Todo from "@/components/Todo/Index.vue";
import { ref } from "vue";
import { getList, delItem, addItem, TYPE_LIST} from "@/utils/todo.ts";
const todoList = ref(getList() as TYPE_LIST);
const del = function (content: string) {
  delItem(todoList.value, content)
};
const add = function (content: string) {
  addItem(todoList.value, content)
};
</script>
<template><Todo :list="todoList" @add="add"  @del="del" /></template>
