// site/react/src/pages/lifeCycle/index.tsx
import React, { useEffect } from "react";
import CodeDemo from "@/components/CodeDemo";

export default function LifeCycle(): React.JSX.Element {
  // useEffect 用于监听组件的生命周期，包括挂载、更新和卸载
  useEffect(() => {
    console.log("react 挂载完成");
    return () => {
      console.log("react 卸载完成");
    };
  }, []);

  return (
    <>
      <div>生命周期</div>
      <CodeDemo />
    </>
  );
}

// site/vue3/src/pages/lifeCycle/index.vue
<script lang="ts" setup>
import CodeDemo from "@/components/CodeDemo";
import { onMounted, onUnmounted } from "vue";

// 生命周期
onMounted(() => {
  console.log("vue 挂载完成");
});
onUnmounted(() => {
  console.log("vue 卸载完成");
});
</script>

<template>
  <div>生命周期</div>
  <CodeDemo :codeData="null" />
</template>
